### ISSUE TITLE
Add Android 5 support

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#218]
Hello,
i have nice, now retro console Nvidie Shield portable, its limited to Android 5, when i try to install apk, im getting that package is corrupted, but when i try same binary install on my phone with Android 8 its fine.. so its probably problem with older Android version.

**Comment by DjThunder** [comment]
Ok I will give a try with an emulated device.

**Comment by DjThunder** [comment]
@ruthan Good news ! I'm now able to support Android 5, maybe you want to give a try ? (especially on performance side... don't know if it will run smooth enough).
