### ISSUE TITLE
Add click and touch support to menu

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#219]
Hello,
i tried game on my phone:
Android 8 Sony Xperia G3221 

But i dont see any virtual keyboard or game pad buttons to control it, unfortunately my phone Bluetooth implementation sucks so i cant use some external gamepad.. but from description it seems that it is not yet supported anyway.

  When i try ti touch screen, im somehow able to change menu items, but im not able to simule fire button press.

**Comment by DjThunder** [comment]
For fire, it is two finger touch at same time.
Virtual keyboard will appear on game scene only and when cheats are enabled.
On menu, keyboard is only represented by screen area (top area = arrow up, down area = arrow down ...)

**Comment by ruthan** [comment]
Its working but its not intuitive at all, you would have to make some Android only code and some overlay buttons or make it working on single finger click..

**Comment by DjThunder** [comment]
I added mouse and touch support to menus (including the new cheats menu), and fire action on intro and extro with simple touch.

**Comment by DjThunder** [comment]
@ruthan 

> But i dont see any virtual keyboard or game pad buttons to control it, unfortunately my phone Bluetooth implementation sucks so i cant use some external gamepad.. but from description it seems that it is not yet supported anyway.

Gamepad support added to Android: #224
