### ISSUE TITLE
Add game launcher configuration

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#221]
Hello,
game window is really tiny on highres monitors as mine.
 Something like simple integer filter to multiple (double/triple) application size would be nicer, later you can even add some clever graphics smoothing options..

  Technically it should be quite simple for double size draw 2x2/3x3 pixels instead of every single pixel, i dont thing that you need to struggle with some in build Java inbuild zooming or drawing options.

**Comment by DjThunder** [comment]
Until next release, you can try this: https://github.com/b3dgs/lionheart-remake/wiki/UserManual#properties
(Modify properties for custom output resolution)
