### ISSUE TITLE
Add Android virtual keyboard diagonal support

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#222]
I tried to play on my phone, virtual controls sucks for gaming.. but for example im able to play Golden Axe on with them, quite well. This game is really hard, full of unforgiving jumping sequences.. it would be hard.
   
  Simply press 2 virtual buttons together for down and left and down  right is not really working well. I suggest make dedicated buttons.. for down+left, down, down+right.. And maybe for left+up,up,right+up.. If some dont want to use jump button, original amiga version have similar options too - 1/2 button joystick with dedicated mapping button.

  If you have some controller/ or Android x86 keyboard, you can use some virtual to physical button mapping apps like Tincore, but even there would be dedicated button much better and easier to map than make some area button to overlay 2 virtual buttons.

**Comment by DjThunder** [comment]
Yes I know inputs are really hardcore. I can play it well, but this is because I know my game.

**Comment by DjThunder** [comment]
![diagonal](https://user-images.githubusercontent.com/5088071/131258484-525e45a6-f645-42b6-8625-ae1c78937613.jpg)
