### ISSUE TITLE
Java: Permission denied.

### ISSUE THREAD

**Issue by Achaean** [b3dgs/lionheart-remake#253]
Latest Lionheart version (1.1), on Devuan ASCII (oldstable) KDE x64.

Downloaded and unpacked the linux64 archive.
Ruining lionheart-remake.sh gave this error and aborted:

```
>./lionheart-remake.sh 
./lionheart-remake.sh: line 4: ./jvm_linux_x86_64/bin/java: Permission denied
>
```
 
Changing the /data/jvm_linux_x86_64/bin//java attribute -> executable, solved the problem.

**Comment by DjThunder** [comment]
Right.
Working fine when transferring from my machine to virtual machine with linux using USB.
But when downloading from my server, executions right are no longer there.

I simply zipped the package from my virtual machine with linux, and reuploaded the archive.
Working fine now.
Thanks !

**Comment by Achaean** [comment]
> Working fine now. Thanks !
> 

And **CONGRATS** for the new release!!!  :-)
