### ISSUE TITLE
Linux libsdl2gdx64 udev missing dependency warning

### ISSUE THREAD

**Issue by Achaean** [b3dgs/lionheart-remake#254]
```
On Devuan ASCII (oldstable) x64 KDE.
>java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-8u302-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)
>
```

When starting, I'm receiving a failure message. (Not sure, what it is).
I'm attaching console's output. (Launching game -> getting the warning message -> game control panel opens -> I'm closing it).

```
>./lionheart-remake.sh
> 2021-10-05 18:06    INFO: Starting "LionEngine "10.0.0" for "Lionheart Remake 1.1.0"
> 2021-10-05 18:06    INFO: Class resources = com.b3dgs.lionheart.AppLionheart
> EXTRACTED LOC /tmp/13024741725922545191.tmp
> NATIVE METHOD: loading from  "/tmp/13024741725922545191.tmp"
>              result 74  Failed loading udev_device_get_action: /tmp/jnigen/375939362/libsdl2gdx64.so: undefined symbol: _udev_device_get_action
>
```

**Comment by DjThunder** [comment]
The game still run ?
This is the library used for gamepad.
Sounds like a missing dynamic dependency around udev.

Try to install this package (just to see): libudev-dev

I don't have this problem with Debian 10. I will try to include this library directly then.

**Comment by Achaean** [comment]
I installed it, but didn't see any difference.

Maybe this is related:
Left Ctrl, can't be assigned.
Other than that, I can't see any defects.

![Screenshot](https://user-images.githubusercontent.com/3608053/136079236-bd91f41f-3c10-45b2-a6f2-4533ed2e1de0.png)

**Comment by DjThunder** [comment]
But gamepad is working on my side, even with warning. Are you using a gamepad ? It should be working.

**Comment by Achaean** [comment]
I don't have a pad nowadays, but it's configuration panel looks flawless.

![Screenshot_PAD](https://user-images.githubusercontent.com/3608053/136086156-2429bc61-4b49-4418-a60f-80f703951023.png)

**Comment by DjThunder** [comment]
Thanks for your time, I will do my best for the warning !

**Comment by DjThunder** [comment]
Can't find where come from the log.
Only way to avoid this log is to redirect to dev null:
`
./jvm_linux_x86_64/bin/java -Xms256M -Xmx256M -server -Dsun.java2d.uiScale=1.0 -splash:splash.png -jar lionheart-pc-1.X.X.jar > /dev/null
`
Game log will still be visible.
