### ISSUE TITLE
Black screen / no window on Linux

### ISSUE THREAD

**Issue by DavidNemeskey** [b3dgs/lionheart-remake#260]
## Actual Behavior

If I start the game in full-screen mode, I get a black screen. In windowed mode, the window is created (so I can exit the game with Alt+F4), but it does not appear on the screen. In either case, the music starts playing, so it is most likely a graphics / windowing bug.

## Steps to Reproduce the Problem

  1. Start the game

## Specifications

  - Lionheart Remake Version: 1.1.0
  - JDK: the one shipped with the game, OpenJDK 17
  - OS: KDE Neon

### Further system information

Operating System: KDE neon 5.22
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-37-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3635QM CPU @ 2.40GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

**Comment by DavidNemeskey** [comment]
BTW a potentially very important information that I have forgot. When running the starting script, I get this error message:
```
XTRACTED LOC /tmp/16768588890523061225.tmp
NATIVE METHOD: loading from  "/tmp/16768588890523061225.tmp"
             result 74  Failed loading udev_device_get_action: /tmp/jnigen/375939362/libsdl2gdx64.so: undefined symbol: _udev_device_get_action
```

I tried installing `libudev-dev`, `libsdl2-dev` and `libsdl1.2-dev` (following advices from various sites), but the error persists.

**Comment by DjThunder** [comment]
This is for gamepad support, but it is not a problem, as it works.
Can you try with scaled to 1 and 4/3 ratio in windowed?

**Comment by DjThunder** [comment]
Maybe driver issue with intregrated. I will try to reproduce it, but not before this weekend unfortunately. Just for fun, you can try with a debian inside a vm...

**Comment by DjThunder** [comment]
Sounds to be related to page flipping and screen buffering. Try with vsync (game speed will be invalid if cant sync on)

**Comment by DjThunder** [comment]
Can you try to redownload it: [link ](https://www.b3dgs.com/v7/projects/lionheart_remake/files/1.1.0/lionheart_remake_1.1.0_linux64.zip)?
I will try to provide an official hotfix 1.1.1 for linux if enough time, else, will be included in next release.

**Comment by DavidNemeskey** [comment]
Sorry, the zip seems to be corrupted, I can only unzip a few files and get `bad zipfile offset` for the rest:
```
Archive:  lionheart_remake_1.1.0_linux64.zip
   creating: lionheart_remake_linux64/
   creating: lionheart_remake_linux64/data/
lionheart_remake_linux64/data/splash.png:  mismatching "local" filename (lionheart_remake_linux64/data/lionheart-pc-1.1.0.jar),
         continuing with "central" filename version
  inflating: lionheart_remake_linux64/data/splash.png  
  error:  invalid compressed data to inflate
file #4:  bad zipfile offset (local header sig):  5356
...
```

**Comment by DjThunder** [comment]
Ok, I reuploaded it, and checked its integrity. Fine on my side. Can you retry ? (sorry)

**Comment by DjThunder** [comment]
Fixed by: https://github.com/b3dgs/lionengine/commit/c861b3989c46a37d27d49eea716213fdf094fb93
