### ISSUE TITLE
License question related to Linux repository integration

### ISSUE THREAD

**Issue by sheepo99** [b3dgs/lionheart-remake#270]
Hello! I just wanted to leave a note of appreciation for creating this project that not only replicates the original game faithfully, but also expands upon it.

As a small suggestion, I maybe it would be a good idea to contact the original creators of the game and ask them if they could agree to license the artwork assets under Public Domain or CC-BY-SA. This would mean that your remake could be freely preserved forever under creative commons and integrate the repositories of many Linux distributions by default!

Best regards,
Sheepo99

**Comment by DjThunder** [comment]
Hello! Thanks for your comment :)

I already talked about license years ago with original team. Indeed, nobody knows where are the original rights. Thalion is the last legal owner, but since the company closed in 1994, licenses may have moved.
What they told me is since my remake is free, nothing should happen, but nobody knows what is the true license statement (if there is one).

**Comment by sheepo99** [comment]
Hi there, and thank you for your reply!

Well, the thing is I was actually interested in submitting this project to the Debian Games Team, with the goal of integrating the game into their main repo. However, only games with art under public domain or CC-BY-SA are allowed... Do you think it would be possible to contact the owners again? I also wouldn't mind contacting them on my own if you can provide an email address.

**Comment by DjThunder** [comment]
I will ask them again if this could be possible.

**Comment by sheepo99** [comment]
Thank you! This is very kind of you!

Unless Thalion and its assets were specifically purchased by a third part after the company went down, the rights should rest with the original artists and creators and their permission should be enough. While releasing old properties to the public domain can sometimes be met by resistance from creators, it benefits everyone by making quality works available for everyone to enjoy and remix entirely for free, much like classical music pieces or old books.

**Comment by DjThunder** [comment]
Yes I see. I will notice you if anything changed.
