### ISSUE TITLE
Add alternative player attack gameplay with more trivial feeling

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#299]
Hello,
i always had problem with default controls of this game, that when you only press attack button, nothing is happening and often want to attack, but character is not attacking because is not pressed attack and directorial arrow together.

  So it would be nice at least optimally add behavior that attack button itself without directory would simulate default attack in directory which is character facing.

   Now when you press attack button alone you got only some half broken animation (there is some glitch on left side of character head), or some half move.. its strange its not usual in other games.

  Same problem is when im press attack button too quickly even when direction key is pressed.. it would be nice again, not get stuck and do nothing but finish previous attack regardless of button smashing..

**Comment by DjThunder** [comment]
Problem with **default attack on side** is removal of prepared attack.
State **prepared** allow to choose between (this is the animation you see when pressing multiple time fire without directional, as if you were stuck to do what you expected):
* top
* horizontal
* turning
* leg

I know this is not common, but this is the charm of this game.
Once you master the combination (fire pressed with good timing, and then directional), this is very satisfying to use variant attack with the right key combination in the right order (simpler with keyboard).

Fore sure, I will try to provide an alternative (choosable) gameplay to answer to this problem.

**Comment by ruthan** [comment]
Thanks very much, i dont mind mark as hack for lamas.. Sometimes its make attack hard as some combo in fighting games, when you are not good in mind, fingers coordination.. I never got that play through whole levels without hit etc, these people are robots to me.

**Comment by ruthan** [comment]
Great, let me now, when it would be released.

**Comment by DjThunder** [comment]
Yes. Selectable gameplay from Launcher (original or alternative).
