### ISSUE TITLE
Add support to stage progress save and load

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#301]
- [x] Add support to stage progress save & load.
- [x] Additional support to quick save / load with in depth data storage (as amiga memory snapshot) if possible (available in debug only, with '/' and '*' key from pavnum).

**Comment by DjThunder** [comment]
I will have a look on this feature.
It is a bit different with emulator, as the whole memory is stored (this is not a game function).
In my case I will need to provide an in depth save with all current locations & vectors & states), but it is possible.
