### ISSUE TITLE
SFX not working on Linux

### ISSUE THREAD

**Issue by sheepo99** [b3dgs/lionheart-remake#302]
I'm running Xubuntu 21.10 and for some reason the SFX are not being properly reproduced in version 1.2.0, although music plays just fine. Both SFX and music play with no issues on version 1.1.0, so I assume there's something amiss in the latest version.

**Comment by DjThunder** [comment]
Corrupted wav file in linux package. Linux dist updated to [1.2.1](https://lionheart.b3dgs.com/files/1.2.0/lionheart-remake-1.2.1_linux64.tar.xz).
