### ISSUE TITLE
Antivirus detections on "Lionheart Remake.exe" launcher

### ISSUE THREAD

**Issue by lunatixxx** [b3dgs/lionheart-remake#304]
Is it possible to fix it ? I know that false positives happens but this is a lot of them actually, i am using bitdefender and it detects a trojan before that i even opened it.

https://www.virustotal.com/gui/file/6def34339b358518cf1fc0570d75b5f27b2a8902288b01a49d14d4e363ee824b/detection

**Comment by DjThunder** [comment]
Ah this is the bat converted to exe runnable I guess. I need to check that and see what can be done to avoid it (of course I can let only the bat file... but less userfriendly. Thx !

**Comment by DjThunder** [comment]
Hum, even with a basic C program compiled to exe with a simple call to system() to run a bat will be detected as trojan. I think it is because of the bat path (which means uncontrolled execution).

**Comment by DjThunder** [comment]
Ok, by changing compilation options and linker flags I reduced to 6 the virus total detection (I can't do less, even with void main I still have 6; I guess this is common without interaction on my side to contact providers to flag them false positive, but I will need to sign my exe, which is basically not possible without paying, or without requesting user to install my certificate).

**Comment by DjThunder** [comment]
I found how to reach 0 report. I will update report with final distribution here.
