### ISSUE TITLE
Liana cut may crash on Android

### ISSUE THREAD

**Issue by ruthan** [b3dgs/lionheart-remake#311]
# TODO
- [x] Improve liana cut performance to reduce computation overhead

# Original comment
## Expected Behavior
Be fluent.

## Actual Behavior
Getting slower and slower to freeze.

## Steps to Reproduce the Problem
Go to first place when you cut trough wall and cut through..
 
## Specifications
Xperia 10 II

  - Lionheart Remake Version: 1.2.0
  - JDK: who knows..
  - OS: Android 11

**Comment by DjThunder** [comment]
You mean when cutting liana ?
I can't reproduce the slowdown.
Do you know the approximate playing duration before slowing down ?
Can you tell me exactly your last location before bug ?

Thx !

**Comment by ruthan** [comment]
Its long time, just green walls which could be destroyed, if remember correctly..

 If was start of game, i guess that is engine problem on low end devices.

**Comment by DjThunder** [comment]
Ah maybe. I will try to optimize at best then.

**Comment by DjThunder** [comment]
I found multiple reason, I i'm fixing them all to make game run smoother on old device.
I tested on an old Samsung A5 (2017) with Android 6, it was almost impossible to approach liana area. Now it is as on computer, as fast (60fps). So it should work for you I hope !

I still need in depth testing, as I rewritten a lot of things, especially on collision computation side (tiles & objects).
