### ISSUE TITLE
Game crashes when starting Android 13

### ISSUE THREAD

**Issue by SSarodnick** [b3dgs/lionheart-remake#356]
## Steps to Reproduce the Problem
  1. Installes
  2. Starts Till choose screen but cant chosse anything.
  3. Crashes. 

## Specifications
  - Lionheart Remake Version: newest Android build
  - OS: Android 13

**Comment by DjThunder** [comment]
I can't reproduce it with an emulated device using Android 13 (and my native is Android 12).
What is your phone / system model ?

**Comment by SSarodnick** [comment]
Its a Asus rog 5s

Pierre-Alexandre ***@***.***> schrieb am Fr., 19. Mai 2023,
16:21:

**Comment by DjThunder** [comment]
Ok. It tested on a S20FE with Android 13, working.
So you have the loading screen, then the menu, but you can't click on anything ? And then crash ?

**Comment by SSarodnick** [comment]
Yes. I start the Game. The Menu ist showing Up but i cant click on anything
and need zu Close the Game.

Pierre-Alexandre ***@***.***> schrieb am Fr., 19. Mai 2023,
17:24:

**Comment by SSarodnick** [comment]
Oooh OK. I need 2 hold the Button to choose anything?
This should work

Pierre-Alexandre ***@***.***> schrieb am Fr., 19. Mai 2023,
17:24:

**Comment by DjThunder** [comment]
First touch will select, and 2nd touch on selected element with perform like a mouse click.
This is to avoid unwanted menu selection, at the cost of two operation to select something.

**Comment by SSarodnick** [comment]
OK so it was fault sorry

Pierre-Alexandre ***@***.***> schrieb am Fr., 19. Mai 2023,
17:43:

**Comment by DjThunder** [comment]
No, it means menu selection is not user-friendly enough. I will try to make it better. Thanks for your time !
So finally, no unexpected crash ?

**Comment by SSarodnick** [comment]
Now everything is perfect and I've already played the first round.

Pierre-Alexandre ***@***.***> schrieb am Fr., 19. Mai 2023,
18:37:
