### ISSUE TITLE
Spider teleport movement after spawn by the 2nd big spider

### ISSUE THREAD

**Issue by Commodusaurel** [b3dgs/lionheart-remake#359]
At the last big spider in the first spider cave, the little spiders will disappear at one point and reappear a little further back, run forward again, disappear, etc.

## Specifications
  - Lionheart Remake Version:  1.3.0
  - OS: WIN 11

**Comment by DjThunder** [comment]
I already experienced something like this a long time ago, I will check this specific spider case (maybe a specific bug with spawning and tracking player) Thx !
