### ISSUE TITLE
Spider Movement in the Second Spider Cave

### ISSUE THREAD

**Issue by Commodusaurel** [b3dgs/lionheart-remake#360]
In the second spider cave, the small daughter spiders of the last giant spider also have the problem of disappearing and respawning at the back

PS: Thanks for the great port of my favorite Amiga game

## Specifications
  - Lionheart Remake Version:  1.3.0
  - OS:  WIN 11 22H2

**Comment by DjThunder** [comment]
Yes I get it, it occurs only if you killed at least on spider, and the killed spider is re-used by the big one for spawn (so after few spawns; patrol data were not reset on respawn).
