### ISSUE TITLE
website is down, unable to build

### ISSUE THREAD

**Issue by ppvnf** [b3dgs/lionheart-remake#369]
Can someone send a mirror download link, I only have version 1.0 if someone wants. I tried building using Maven but I get some dependency errors

**Comment by DjThunder** [comment]
What are your dependencies errors ? Everything is hosted on maven central, so it should not be related to my website (which is currently offline).

**Comment by DjThunder** [comment]
Website should be working (problem with DNS). You can clear your DNS cache to make it work now, or await up to 24h.

**Comment by ppvnf** [comment]
Ok, now it works!! thank you very much!
