### ISSUE TITLE
Crash of the game during starting under Mac OS.

### ISSUE THREAD

**Issue by TodorBalabanov** [b3dgs/lionheart-remake#82]
## Expected Behavior

Game to run.

## Actual Behavior

Game crash after run from the command line.

## Steps to Reproduce the Problem

  1. Build PC version for Mac OS.
  2. Run from command line.

## Specifications

  - Lionheart Remake Version: 0.0.17
  - JDK: 1.8.0_91
  - OS: Mac OS

[err.txt](https://github.com/b3dgs/lionheart-remake/files/4010236/err.txt)

**Comment by DjThunder** [comment]
Try to remove this line
World : line 192
`factory.createCache(Medias.create(Folder.EFFECTS), 5);`

It tries to list files from directory inside JAR. Perhaps not working on Mac (not tested on Linux yet...).

**Comment by DjThunder** [comment]
Can you try with the latest tag [0.1.0](https://github.com/b3dgs/lionheart-remake/releases/tag/lionheart-0.1.0) ?

**Comment by DjThunder** [comment]
The final release is also available.
